name             'BERK_COOKBOOK'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures BERK_COOKBOOK'
long_description 'Installs/Configures BERK_COOKBOOK'
version          '0.1.0'
